// Import images (make sure to replace these with your actual image imports)
import aird1 from "../diaryImages/air/air2.jpg";
import aird from "../diaryImages/air/air3.jpg";
import earthGif from "../diaryImages/earth/earth4.png";
import earthGif1 from "../diaryImages/earth/earth5.png";
import fireGif1 from "../diaryImages/fire/fire3.jpg";
import fireGif from "../diaryImages/fire/fire4.png";
import waterGif from "../diaryImages/water/water3.png";
import waterGif1 from "../diaryImages/water/water33.png";

export const ELEMENT_DESCRIPTIONS = {
  fire: {
    words: ["", "FIRE"],
    description:
      "Fire symbolizes passion, energy, and transformation. Discover your inner strength and motivation.",
    colors: ["#D70040", "#4A0404"],
    image: fireGif,
    altImage: fireGif1,
  },
  water: {
    words: ["", "WATER"],
    description:
      "Water represents emotions, intuition, and adaptation. Learn to flow with the stream of life.",
    colors: ["#1434A4", "#00FFFF"],
    image: waterGif,
    altImage: waterGif1,
  },
  air: {
    words: ["", "AIR"],
    description:
      "Air stands for intellect, communication, and creativity. Develop your thinking and self-expression skills.",
    colors: ["#ADD8E6", "white"],
    image: aird,
    altImage: aird1,
  },
  earth: {
    words: ["", "EARTH"],
    description:
      "Earth symbolizes stability, growth, and renewal. Find your roots and build solid foundations.",
    colors: ["#355E3B", "#7CFC00"],
    image: earthGif,
    altImage: earthGif1,
  },
};
export const advices = [
  {
    element: "fire",
    text: "Fire can melt metals with low melting points, such as lead or aluminum.",
    color: "#D70040",
  },
  {
    element: "water",
    text: "Under certain conditions, water can exist in a triple-phase state, simultaneously as a solid (ice), liquid (water), and gas (water vapor).",
    color: "#00FFFF",
  },
  {
    element: "air",
    text: "Air pressure decreases with altitude, which is why it becomes more challenging to breathe at higher elevations.",
    color: "#87CEEB",
  },
  {
    element: "earth",
    text: "The Earth's crust is divided into tectonic plates that constantly move, leading to the formation of continents and geological phenomena like earthquakes and volcanoes.",
    color: "#90EE90",
  },
  {
    element: "fire",
    text: "Fire is the only element that humans can control and use for various purposes.",
    color: "#D70040",
  },
  {
    element: "water",
    text: "Water has the incredible ability to disperse sound, making it an excellent medium for underwater sound transmission.",
    color: "#00FFFF",
  },
  {
    element: "air",
    text: "Air is essential for human survival and contains approximately 78% nitrogen, 21% oxygen, and trace amounts of other gases.",
    color: "#87CEEB",
  },
  {
    element: "earth",
    text: "Soil is a vital part of Earth's ecosystem and contains a rich diversity of organisms, including bacteria, fungi, and insects, essential for plant growth.",
    color: "#90EE90",
  },
  {
    element: "fire",
    text: "In ancient cultures, fire was often associated with transformation and purification rituals.",
    color: "#D70040",
  },
  {
    element: "water",
    text: "Water covers about 71% of the Earth's surface and is essential for the existence of life.",
    color: "#00FFFF",
  },
  {
    element: "air",
    text: "Wind energy, harnessed from the air's movement, is a sustainable and renewable source of power.",
    color: "#87CEEB",
  },
  {
    element: "earth",
    text: "The Earth's magnetic field, generated by its iron-nickel core, protects the planet from harmful solar winds.",
    color: "#90EE90",
  },
  {
    element: "fire",
    text: "Fire has been used throughout history for cooking, heating, and providing light in the darkness.",
    color: "#D70040",
  },
  {
    element: "water",
    text: "Water is a universal solvent, capable of dissolving a wide variety of substances, making it essential for chemical processes in living organisms.",
    color: "#00FFFF",
  },
  {
    element: "air",
    text: "The ozone layer in the Earth's atmosphere absorbs and protects life on Earth from harmful ultraviolet (UV) radiation.",
    color: "#87CEEB",
  },
  {
    element: "earth",
    text: "Plants play a crucial role in Earth's carbon cycle, absorbing carbon dioxide during photosynthesis and releasing oxygen.",
    color: "#90EE90",
  },
];

export const texts = [
  "Discover how understanding the four elements - Fire, Water, Air, and Earth - can help you in your journey of self-development. Embrace the unique qualities of each element to find balance and harmony in your life.",
  "Explore the power of the four elements - Fire, Water, Air, and Earth - and see how they influence your daily life. Allow yourself a deeper understanding of these fundamental forces to better harmonize with the world around you.",
];
